EARLY_VOTING_STATES = [
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'District of Columbia',
    'Florida',
    'Georgia',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Louisiana',
    'Maine',
    'Maryland',
    'Missuori',
    'Nebraska',
    'Nevada',
    'New Mexico',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'West Virginia',
    'Wisconsin',
    'Wyoming',
]
